### ISSUE TITLE
Option to specify static content to copy to build directory

### ISSUE THREAD

**Issue by Flet** [ngoldman/sitedown#5]
Its probably common that a generated site would use some css/js/images to make it look pretty.

Does it make sense to build that into `sitedown`, or should users just handle this outside of this command (via a simple `cp` in their build script perhaps)?

Would you prefer `sitedown` stay focused on the transformation of markdown only?

**Comment by ngoldman** [comment]
There's a decent argument for both... I think the advantage of sitedown right now is that it is very narrowly focused. Because of how negligible it would be to copy static files after sitedown does its main job, I would argue in favor of keeping sitedown focused on transformation and let `cp` or something like that do the work of static assets.

You could have something like this do the job:

```json
"scripts": {
  "prebuild": "rm -rf build",
  "build": "sitedown --header partials/_header.html --footer partials/_footer.html",
  "postbuild": "cp assets build"
}
```

**Comment by Flet** [comment]
For sure! Makes a lot of sense
